export interface HeaderItem {
    gen_row_define_id: { v: number; r: number };
    table_id: { v: number; r: number };
    table_name: { v: string; r: string };
    is_primary_key: { v: number; r: number };
    display_order: { v: number | null; r: number | null };
    name: { v: string; r: string };
    en_name: { v: string; r: string };
    vn_name: { v: string; r: string };
    ja_name: { v: string; r: string };
    is_nullable: { v: number | null; r: number | null };
    is_visible: { v: number | null; r: number | null };
    list_order: { v: number | null; r: number | null };
    row_ref_id: { v: number | null; r: number | null };
    editable_users: { v: string; r: string };
    data_type: { v: number | null; r: number | null };
    data_size: { v: number | null; r: number | null };
    editable_user_groups: { v: unknown; r: unknown };
    status: { v: unknown; r: unknown };
    type_option: { v: unknown; r: unknown };
    edit_order: { v: unknown; r: unknown };
    is_reference_visible: { v: unknown; r: unknown };
    default_value: { v: unknown; r: unknown };
    reference_condition: { v: unknown; r: unknown };
    reference_type: { v: unknown; r: unknown };
    unique_type: { v: unknown; r: unknown };
    column_group: { v: number | null; r: number | null };
    band_group: { v: unknown; r: unknown };
    band_order: { v: unknown; r: unknown };
    equivalent_value: { v: unknown; r: unknown };
    display_value_member: { v: unknown; r: unknown };
    multi_reference_condition: { v: unknown; r: unknown };
    report_format: { v: unknown; r: unknown };
    export_column: { v: unknown; r: unknown };
    main_linked_table_column: { v: unknown; r: unknown };
    sort_order: { v: unknown; r: unknown };
    search_constraint: { v: unknown; r: unknown };
    search_type: { v: unknown; r: unknown };
    is_searchable: { v: unknown; r: unknown };
    auto_complete_columns: { v: unknown; r: unknown };
    breadcrumb_order: { v: unknown; r: unknown };
    column_width: { v: string; r: string };
    html_before_insert: { v: unknown; r: unknown };
    html_after_insert: { v: unknown; r: unknown };
    is_editable: { v: number; r: number };
    is_changeable: { v: unknown; r: unknown };
    input_mask: { v: unknown; r: unknown };
    html_input: { v: unknown; r: unknown };
    display_format: { v: unknown; r: unknown };
    summary_type: { v: unknown; r: unknown };
    reference_column_name: { v: unknown; r: unknown };
    is_hyperlink: { v: unknown; r: unknown };
    restricted_user_groups: { v: unknown; r: unknown };
    column_width_size: { v: unknown; r: unknown };
    column_width_web_v2: { v: unknown; r: unknown };
    computed_expression: { v: unknown; r: unknown };
    true_column_name: { v: string; r: string };
    alias_name: { v: unknown; r: unknown };
    input_regex: { v: string; r: string };
    input_regex_message: { v: string; r: string };
    column_class: { v: unknown; r: unknown };
    has_background: { v: unknown; r: unknown };
    editable_condition: { v: unknown; r: unknown };
    default_filter: { v: string; r: string };
    is_unique_selection: { v: unknown; r: unknown };
    allowed_file_types: { v: unknown; r: unknown };
    is_datetime_disabled: { v: unknown; r: unknown };
    is_mandatory_search: { v: unknown; r: unknown };
    tree_structure_table: { v: unknown; r: unknown };
    merged_column: { v: unknown; r: unknown };
    child_tab_display_condition: { v: unknown; r: unknown };
    header_group: { v: unknown; r: unknown };
    column_placeholder: { v: unknown; r: unknown };
    allow_special_char: { v: unknown; r: unknown };
    input_options: { v: unknown; r: unknown };
    output_options: { v: unknown; r: unknown };
    modified_by: { v: unknown; r: unknown };
    modified_at: { v: unknown; r: unknown };
    created_by: { v: unknown; r: unknown };
    created_at: { v: string; r: string };
    record_status: { v: unknown; r: unknown };
    record_log: { v: unknown; r: unknown };
}